pipeline {
    agent any
    stages {
        stage('Building frontend') {
            when {
                branch "main"
            }
            environment {
                GIT_PASSWORD = credentials('github')
                DOCKER_CREDS = credentials('docker-creds')
                FACEBOOK_APP_ID = credentials('facebook-app-id')
                GOOGLE_APP_ID = credentials('google-app-id')
                REACT_APP_SITEKEY = credentials('react-app-sitekey')
            }
            steps {
								sh(returnStdout: true, script: "bash -e /var/jenkins_home/scripts/frontend/build.sh")
						}
        }
        stage('Deploying frontend') {
            when {
                branch "main"
            }
            steps {
                sh(returnStdout: true, script: "bash -e /var/jenkins_home/scripts/backend/deploy.sh")
            }
        }
    }
}
