import { styled } from '@mui/material';

export const JoinCommunity = styled('button')({
  position: 'relative',
  border: '1px solid #0079d3',
  color: 'white',
  fill: '#0079d3',
  backgroundColor: '#0079d3',
  width: 96,
  fontFamily: 'Noto Sans,Arial,sans-serif',
  fontSize: 14,
  fontWeight: 700,
  letterSpacing: 'unset',
  textTransform: 'unset',
  minHeight: 32,
  minWidth: 32,
  padding: '4px 16px',
  cursor: 'pointer',
  alignItems: 'center',
  borderRadius: 9999,
  boxSizing: 'border-box',
  display: 'flex',
  justifyContent: 'center',
  textAlign: 'center',
});
export const Join = styled('button')({
  position: 'relative',
  border: '1px solid #0079d3',
  color: '#0079d3',
  fill: '#0079d3',
  width: 96,
  fontFamily: 'Noto Sans,Arial,sans-serif',
  fontSize: 14,
  fontWeight: 700,
  letterSpacing: 'unset',
  textTransform: 'unset',
  minHeight: 32,
  minWidth: 32,
  padding: '4px 16px',
  background: 'transparent',
  cursor: 'pointer',
  alignItems: 'center',
  borderRadius: 9999,
  boxSizing: 'border-box',
  display: 'flex',
  justifyContent: 'center',
  textAlign: 'center',
});
